{{- if .Values.gitWebhookProxy.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- if .Values.gitWebhookProxy.ingress.annotations }}
  annotations:
{{ toYaml .Values.gitWebhookProxy.ingress.annotations | indent 4 }}
{{- end }}
  labels:
{{ include "gitwebhookproxy.labels.stakater" . | indent 4 }}
{{ include "gitwebhookproxy.labels.chart" . | indent 4 }}
{{- if .Values.gitWebhookProxy.useCustomName }}
  name: {{ .Values.gitWebhookProxy.customName }}
{{- else }}
  name: {{ template "gitwebhookproxy.name" . }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.gitWebhookProxy.ingress.host }}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
        {{- if .Values.gitWebhookProxy.useCustomName }}
          service:
            name: {{ .Values.gitWebhookProxy.customName }}
            port:
              number: {{ .Values.gitWebhookProxy.servicePort }}
        {{- else }}
          service:
            name: {{ template "gitwebhookproxy.name" . }}
            port:
              number: {{ .Values.gitWebhookProxy.servicePort }}
  tls:
  - hosts:
    - {{ .Values.gitWebhookProxy.ingress.host }}
  {{- if .Values.gitWebhookProxy.ingress.tlsSecretName }}
    secretName: {{ .Values.gitWebhookProxy.ingress.tlsSecretName }}
  {{- end }}
{{- end }}
