---
# Source: gitwebhookproxy/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
  labels:
    app: gitwebhookproxy
    group: com.stakater.platform
    provider: stakater
    version: v0.2.74
    chart: "gitwebhookproxy-v0.2.74"
    release: "gitwebhookproxy"
    heritage: "Tiller"
  name: gitwebhookproxy
data:
    provider: github
    upstreamURL: https://jenkins.tools.stackator.com
    allowedPaths: /github-webhook,/project
    ignoredUsers: stakater-user
    allowedUsers: myuser

---
# Source: gitwebhookproxy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitwebhookproxy
    group: com.stakater.platform
    provider: stakater
    version: v0.2.74
    chart: "gitwebhookproxy-v0.2.74"
    release: "gitwebhookproxy"
    heritage: "Tiller"
  annotations:
    configmap.reloader.stakater.com/reload: gitwebhookproxy
    secret.reloader.stakater.com/reload: gitwebhookproxy
  name: gitwebhookproxy
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: gitwebhookproxy
      group: com.stakater.platform
      provider: stakater
  template:
    metadata:
      labels:
        app: gitwebhookproxy
        group: com.stakater.platform
        provider: stakater
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GWP_PROVIDER
          valueFrom:
            configMapKeyRef:
              key: provider
              name: gitwebhookproxy
        - name: GWP_UPSTREAMURL
          valueFrom:
            configMapKeyRef:
              key: upstreamURL
              name: gitwebhookproxy
        - name: GWP_ALLOWEDPATHS
          valueFrom:
            configMapKeyRef:
              key: allowedPaths
              name: gitwebhookproxy
        - name: GWP_IGNOREDUSERS
          valueFrom:
            configMapKeyRef:
              key: ignoredUsers
              name: gitwebhookproxy
        - name: GWP_ALLOWEDUSERS
          valueFrom:
            configMapKeyRef:
              key: allowedUsers
              name: gitwebhookproxy
        - name: GWP_SECRET
          valueFrom:
            secretKeyRef:
              key: secret
              name: gitwebhookproxy
        image: "stakater/gitwebhookproxy:v0.2.74"
        imagePullPolicy: IfNotPresent
        name: gitwebhookproxy
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5

---
# Source: gitwebhookproxy/templates/ingress.yaml


---
# Source: gitwebhookproxy/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  labels:
    app: gitwebhookproxy
    group: com.stakater.platform
    provider: stakater
    version: v0.2.74
    chart: "gitwebhookproxy-v0.2.74"
    release: "gitwebhookproxy"
    heritage: "Tiller"
  name: gitwebhookproxy
data:
    secret: ""

---
# Source: gitwebhookproxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitwebhookproxy
    group: com.stakater.platform
    provider: stakater
    version: v0.2.74
    chart: "gitwebhookproxy-v0.2.74"
    release: "gitwebhookproxy"
    heritage: "Tiller"
    expose: "true"
    
  name: gitwebhookproxy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gitwebhookproxy
    group: com.stakater.platform
    provider: stakater
